/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const CATEGORIES = {
  medical: {
    label: 'Medical',
    icon: 'HeartPulse',
    color: 'text-red-500',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-200',
    keywords: ['pain', 'blood', 'heart', 'breath', 'accident', 'injury', 'sick', 'doctor', 'ambulance', 'hospital', 'wound', 'stroke', 'unconscious', 'chest pain', 'bleeding', 'labor', 'pregnant', 'seizure', 'choking', 'allergic', 'poison'],
    department: 'Hospital / Emergency Medical Service',
    helpline: '108',
    nearbySearchType: 'hospital',
  },
  fire: {
    label: 'Fire',
    icon: 'Flame',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-200',
    keywords: ['fire', 'smoke', 'burn', 'explosion', 'gas', 'flame', 'spark'],
    department: 'Fire Safety & Rescue',
    helpline: '101',
    nearbySearchType: 'fire_station',
  },
  police: {
    label: 'Police',
    icon: 'ShieldAlert',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-200',
    keywords: ['theft', 'attack', 'robbery', 'fight', 'danger', 'secure', 'threat', 'crime', 'police', 'weapon', 'assault'],
    department: 'Local Police Precinct',
    helpline: '100',
    nearbySearchType: 'police',
  },
  cybercrime: {
    label: 'Cyber Crime',
    icon: 'GlobeLock',
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-200',
    keywords: ['fraud', 'phishing', 'scam', 'hacker', 'password', 'online'],
    department: 'Cyber Crime Cell',
    helpline: '1930',
    nearbySearchType: 'police',
  },
  domestic: {
    label: 'Domestic Help',
    icon: 'HeartHandshake',
    color: 'text-rose-600',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-200',
    keywords: ['violence', 'abuse', 'beating', 'domestic'],
    department: 'Women & Child Dept',
    helpline: '1091',
    nearbySearchType: 'police',
  },
  animal: {
    label: 'Animal Rescue',
    icon: 'Dog',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-200',
    keywords: ['dog', 'cat', 'stray', 'animal', 'cow', 'monkey'],
    department: 'Veterinary Dept',
    helpline: '1962',
    nearbySearchType: 'veterinary_care',
  },
  lights: {
    label: 'Street Lights',
    icon: 'Lamp',
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-200',
    keywords: ['dark', 'street light', 'lamp', 'bulb'],
    department: 'Municipal PWD',
    helpline: '1912',
    nearbySearchType: 'local_government_office',
  },
  toilets: {
    label: 'Sanitation',
    icon: 'Droplets',
    color: 'text-blue-400',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-100',
    keywords: ['toilet', 'sanitation', 'sewer', 'smell'],
    department: 'SBM Cell',
    helpline: '1969',
    nearbySearchType: 'local_government_office',
  },
  noise: {
    label: 'Noise Control',
    icon: 'VolumeX',
    color: 'text-slate-600',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-200',
    keywords: ['noise', 'loud', 'speaker', 'music', 'construction'],
    department: 'Environmental Cell',
    helpline: '112',
    nearbySearchType: 'police',
  },
  transit: {
    label: 'Pub Transport',
    icon: 'Bus',
    color: 'text-red-600',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-100',
    keywords: ['bus', 'metro', 'train', 'auto', 'overcharge'],
    department: 'Transport Dept',
    helpline: '1073',
    nearbySearchType: 'transit_station',
  },
  traffic: {
    label: 'Traffic Infra',
    icon: 'Activity',
    color: 'text-orange-700',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-200',
    keywords: ['signal', 'traffic light', 'sign', 'board'],
    department: 'Traffic Police',
    helpline: '103',
    nearbySearchType: 'police',
  },
  building: {
    label: 'Bldg Safety',
    icon: 'Construction',
    color: 'text-stone-700',
    bgColor: 'bg-stone-50',
    borderColor: 'border-stone-200',
    keywords: ['crack', 'building', 'fall', 'illegal'],
    department: 'Town Planning',
    helpline: '1070',
    nearbySearchType: 'fire_station',
  },
  records: {
    label: 'Registry',
    icon: 'FileText',
    color: 'text-blue-800',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-200',
    keywords: ['birth', 'death', 'certificate', 'voter', 'id', 'record'],
    department: 'Registrar Office',
    helpline: '1912',
    nearbySearchType: 'local_government_office',
  },
  water: {
    label: 'Water supply',
    icon: 'Droplets',
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-200',
    keywords: ['water', 'leak', 'drain', 'overflow', 'sewage', 'pipe', 'burst', 'tap'],
    department: 'Water Supply & Sewerage Board',
    helpline: '1916',
    nearbySearchType: 'local_government_office',
  },
  electricity: {
    label: 'Electricity',
    icon: 'Zap',
    color: 'text-amber-500',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-200',
    keywords: ['power', 'electricity', 'outage', 'shock', 'cable', 'transformer', 'sparking', 'blackout', 'short circuit'],
    department: 'Electricity Distribution Board',
    helpline: '1912',
    nearbySearchType: 'local_government_office',
  },
  roads: {
    label: 'Roads/Potholes',
    icon: 'Milestone',
    color: 'text-stone-600',
    bgColor: 'bg-stone-50',
    borderColor: 'border-stone-200',
    keywords: ['pothole', 'road', 'street', 'pavement', 'asphalt', 'traffic light', 'blockage'],
    department: 'Public Works Department (PWD)',
    helpline: '1073',
    nearbySearchType: 'local_government_office',
  },
  waste: {
    label: 'Waste Mgmt',
    icon: 'Trash2',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    keywords: ['garbage', 'trash', 'waste', 'smell', 'dumping', 'litter', 'collection'],
    department: 'Municipal Waste Management',
    helpline: '1969',
    nearbySearchType: 'local_government_office',
  },
  crop: {
    label: 'Crop/Farm',
    icon: 'Leaf',
    color: 'text-green-600',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-200',
    keywords: ['pest', 'crop', 'plant', 'farm', 'disease', 'insect', 'soil', 'yield', 'drought'],
    department: 'Agri-Extension Center',
    helpline: '1551',
    nearbySearchType: 'local_government_office',
  },
  general: {
    label: 'General Help',
    icon: 'HelpCircle',
    color: 'text-slate-600',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-200',
    keywords: [],
    department: 'Civic Help Desk',
    helpline: '100',
    nearbySearchType: 'police',
  },
};

export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { code: 'kn', label: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    hero_title: "RescueRouter",
    hero_subtitle: "Precision Emergency Dispatch",
    describe_situation: "Describe Situation",
    voice_assistant: "Voice Assistant",
    camera_analysis: "Camera Analysis",
    sos_button: "SOS TRIGGER",
    analyzing: "Analyzing Report...",
    department: "Department",
    urgency_alert: "Urgency Alert",
    initializing: "Status: Initializing Dispatch",
    primary_dept: "Primary Department",
    helpline: "Helpline",
    nearby_resources: "Nearby Resources",
    gps_request: "Request GPS",
    response_protocols: "Response Protocols",
    core_emergency: "Core Emergency",
    civic_services: "Civic Services",
    medical: "Medical Help",
    fire: "Fire Brigade",
    police: "Police Dept",
    cybercrime: "Cyber Fraud",
    water: "Water Supply",
    electricity: "Power Grid",
    roads: "Roads/PWD",
    waste: "Waste Mgmt",
    noise: "Noise Control",
    msg_medical: "I have a medical emergency",
    msg_fire: "There is a fire emergency",
    msg_police: "I need police assistance",
    msg_water: "Water leakage in my area",
    msg_electricity: "Total power cut in my street",
    msg_cybercrime: "I suspect a cyber financial fraud",
    msg_noise: "Excessive noise in neighborhood",
  },
  hi: {
    hero_title: "रेस्क्यू राउटर",
    hero_subtitle: "सटीक आपातकालीन प्रेषण",
    describe_situation: "स्थिति का वर्णन करें",
    voice_assistant: "आवाज सहायक",
    camera_analysis: "कैমरा विश्लेषण",
    sos_button: "एसओएस ट्रिगर",
    analyzing: "रिपोर्ट का विश्लेषण...",
    department: "विभाग",
    urgency_alert: "आपातकालीन चेतावनी",
    initializing: "स्थिति: प्रेषण शुरू हो रहा है",
    primary_dept: "प्राथमिक विभाग",
    helpline: "हेल्पलाइन",
    nearby_resources: "नजदीकी संसाधन",
    gps_request: "जीपीएस अनुरोध",
    response_protocols: "प्रतिक्रिया प्रोटोकॉल",
    core_emergency: "मुख्य आपात स्थिति",
    civic_services: "नागरिक सेवाएं",
    medical: "चिकित्सा सहायता",
    fire: "दमकल विभाग",
    police: "पुलिस विभाग",
    cybercrime: "साइबर धोखाधड़ी",
    water: "पानी की आपूर्ति",
    electricity: "बिजली ग्रिड",
    roads: "सड़क/पीडब्ल्यूडी",
    waste: "कচरा प्रबंधन",
    noise: "ध्वनि नियंत्रण",
    msg_medical: "मुझे मेडिकल इमरजेंसी है",
    msg_fire: "यहाँ आग लगी है",
    msg_police: "मुझे पुलिस सहायता की आवश्यकता है",
    msg_water: "मेरे क्षेत्र में पानी का रिसाవ है",
    msg_electricity: "मेरी गली में पूरी तरह से बिजली गुल है",
    msg_cybercrime: "मुझे साइबर धोखाधड़ी का संदेह है",
    msg_noise: "पड़ोस में अत्यधिक शोर हो रहा है",
  },
  kn: {
    hero_title: "ರೆಸ್ಕ್ಯೂ ರೌಟರ್",
    hero_subtitle: "ನಿಖರವಾದ ತುರ್ತು ರವಾನೆ",
    describe_situation: "ಪರಿಸ್ಥಿತಿಯನ್ನು ವಿವರಿಸಿ",
    voice_assistant: "ಧ್ವನಿ ಸಹಾಯಕ",
    camera_analysis: "ಕ್ಯಾಮೆರಾ ವಿಶ್ಲೇಷಣೆ",
    sos_button: "SOS ಪ್ರಚೋದಕ",
    analyzing: "ವರದಿಯನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    department: "ಇಲಾಖೆ",
    urgency_alert: "ತುರ್ತು ಎಚ್ಚರಿಕೆ",
    initializing: "ಸ್ಥಿತಿ: ರವಾನೆ ಪ್ರಾರಂಭಿಸಲಾಗುತ್ತಿದೆ",
    primary_dept: "ಪ್ರಾಥಮಿಕ ಇಲಾಖೆ",
    helpline: "ಹೆಲ್ಪ್‌ಲೈನ್",
    nearby_resources: "ಹತ್ತಿರದ ಸಂಪನ್ಮೂಲಗಳು",
    gps_request: "GPS ವಿನಂತಿ",
    response_protocols: "ಪ್ರತಿಕ್ರಿಯೆ ಪ್ರೋಟೋಕಾಲ್‌ಗಳು",
    core_emergency: "ಕೋರ್ ತುರ್ತು",
    civic_services: "ನಾಗರಿಕ ಸೇವೆಗಳು",
    medical: "ವೈದ್ಯಕೀಯ ಸಹಾಯ",
    fire: "ಅಗ್ನಿ ಶಾಮಕ ದಳ",
    police: "ಪೊಲೀಸ್ ಇಲಾಖೆ",
    cybercrime: "ಸೈಬರ್ ವಂಚನೆ",
    water: "ನೀರು ಸರಬರಾಜು",
    electricity: "ವಿದ್ಯುತ್ ಗ್ರಿಡ್",
    roads: "ರಸ್ತೆಗಳು/PWD",
    waste: "ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆ",
    noise: "ಶಬ್ದ ನಿಯಂತ್ರಣ",
    msg_medical: "ನನಗೆ ವೈದ್ಯಕೀಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿ ಇದೆ",
    msg_fire: "ಇಲ್ಲಿ ಬೆಂಕಿ ಅವಘಡ ಸಂಭವಿಸಿದೆ",
    msg_police: "ನನಗೆ ಪೊಲೀಸ್ ಸಹಾಯ ಬೇಕು",
    msg_water: "ನನ್ನ ಪ್ರದೇಶದಲ್ಲಿ ನೀರು ಸೋರಿಕೆಯಾಗುತ್ತಿದೆ",
    msg_electricity: "ನನ್ನ ರಸ್ತೆಯಲ್ಲಿ ಸಂಪೂರ್ಣ ವಿದ್ಯುತ್ ಕಡಿತವಾಗಿದೆ",
    msg_cybercrime: "ನನಗೆ ಸೈಬರ್ ವಂಚನೆಯ ಶಂಕೆಯಿದೆ",
    msg_noise: "ನೆರೆಹೊರೆಯಲ್ಲಿ ಅತಿಯಾದ ಶಬ್ದ ಬರುತ್ತಿದೆ",
  },
  bn: {
    hero_title: "রেসকিউ রাউটার",
    hero_subtitle: "নির্ভুল জরুরি অবস্থা ব্যবস্থাপনা",
    describe_situation: "পরিস্থিতি বর্ণনা করুন",
    voice_assistant: "ভয়েস অ্যাসিস্ট্যান্ট",
    camera_analysis: "ক্যামেরা বিশ্লেষণ",
    sos_button: "SOS সংকেত",
    analyzing: "বিশ্লেষণ করা হচ্ছে...",
    department: "বিভাগ",
    urgency_alert: "জরুরি সতর্কবার্তা",
    initializing: "অবস্থা: ডিসপ্যাচ শুরু হচ্ছে",
    primary_dept: "প্রধান বিভাগ",
    helpline: "হেল্পলাইন",
    nearby_resources: "নিকটস্থ সম্পদ",
    gps_request: "GPS অনুরোধ",
    response_protocols: "প্রতিক্রিয়া প্রোটোকল",
    core_emergency: "মূল জরুরি অবস্থা",
    civic_services: "পৌর পরিষেবা",
    medical: "চিকিৎসা সহায়তা",
    fire: "দমকল বিভাগ",
    police: "পুলিশ বিভাগ",
    cybercrime: "সাইবার অপরাধ",
    water: "জল সরবরাহ",
    electricity: "বিদ্যুৎ গ্রিಡ್",
    roads: "রাস্তাঘাট/PWD",
    waste: "বর্জ্য ব্যবস্থাপনা",
    noise: "শব্দ নিয়ন্ত্রণ",
  },
  te: {
    hero_title: "రెస్క్యూ రూటర్",
    hero_subtitle: "ఖచ్చితమైన అత్యవసర పంపిణీ",
    describe_situation: "పరిస్థితిని వివరించండి",
    voice_assistant: "వాయిస్ అసిస్టెంట్",
    camera_analysis: "కెమెరా విశ్లేషణ",
    sos_button: "SOS ట్రిగ్గర్",
    analyzing: "నివేదికను విశ్ಲೇషిస్తోంది...",
    department: "విభాగం",
    urgency_alert: "అత్యవసర హెచ్చరిక",
    initializing: "స్థితి: డిస్పాచ్ ప్రారంభించబడింది",
    primary_dept: "ప్రాథమిక విభాగం",
    helpline: "హెల్ప్‌లైన్",
    nearby_resources: "సమీప వనరులు",
    gps_request: "GPS అభ్యర్థన",
    response_protocols: "ప్రతిస్పందన ప్రోటోకాల్స్",
    core_emergency: "కోర్ ఎమర్జెన్సీ",
    civic_services: "పౌర సేవలు",
    medical: "వైద్య సహాయం",
    fire: "అగ్నిమాపక దళం",
    police: "పోలీసు విభాగం",
    cybercrime: "సైబర్ మోసం",
    water: "నీటి సరఫరా",
    electricity: "పవర్ గ్రిడ్",
    roads: "రోడ్లు/PWD",
    waste: "వ్యర్థాల నిర్వహణ",
    noise: "శబ్ద నియంత్రణ",
  },
  ta: {
    hero_title: "ரெஸ்க்யூ ரூட்டர்",
    hero_subtitle: "துல்லியமான அவசர விநியோகம்",
    describe_situation: "சூழ்நிலையை விளக்கவும்",
    voice_assistant: "குரல் உதவியாளர்",
    camera_analysis: "கேமரா பகுப்பாய்வு",
    sos_button: "SOS தூண்டுதல்",
    analyzing: "அறிக்கையை பகுப்பாய்வு செய்கிறது...",
    department: "துறை",
    urgency_alert: "அவசர எச்சரிக்கை",
    initializing: "நிலை: விநியோகம் தொடங்குகிறது",
    primary_dept: "முதன்மைத் துறை",
    helpline: "உதவி எண்",
    nearby_resources: "அருகிலுள்ள வளங்கள்",
    gps_request: "GPS கோரிக்கை",
    response_protocols: "பதிலளிப்பு நெறிமுறைகள்",
    core_emergency: "முக்கிய அவசரநிலை",
    civic_services: "நகராட்சி சேவைகள்",
    medical: "மருத்துவ உதவி",
    fire: "தீயணைப்பு படை",
    police: "காவல்துறை",
    cybercrime: "சைபர் மோசடி",
    water: "தண்ணீர் விநியோகம்",
    electricity: "மின்சார கட்டம்",
    roads: "சாலைகள்/PWD",
    waste: "கழிவு மேலாண்மை",
    noise: "சத்தம் கட்டுப்பாடு",
  }
};

export const URGENCY_LEVELS = {
  high: {
    label: 'High Urgency',
    icon: 'AlertOctagon',
    color: 'text-red-700',
    bgColor: 'bg-red-100',
    statusColor: 'bg-red-500',
  },
  medium: {
    label: 'Medium Urgency',
    icon: 'AlertTriangle',
    color: 'text-yellow-700',
    bgColor: 'bg-yellow-100',
    statusColor: 'bg-yellow-500',
  },
  low: {
    label: 'Low Urgency',
    icon: 'Info',
    color: 'text-green-700',
    bgColor: 'bg-green-100',
    statusColor: 'bg-green-500',
  },
};

export const getCategory = (key: string) => {
  return CATEGORIES[key as keyof typeof CATEGORIES] || CATEGORIES.general;
};

export const getUrgency = (key: string) => {
  return URGENCY_LEVELS[key as keyof typeof URGENCY_LEVELS] || URGENCY_LEVELS.low;
};

export const EMERGENCY_NUMBERS = {
  GENERAL: '112', // Universal Emergency Number in India
  MEDICAL: '108',
  FIRE: '101',
  POLICE: '100',
};
